[2m2025-07-06 13:56:02[0m [[31m[1merror    [0m] [1mExecution failed: Traceback (most recent call last):

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/main.py", line 287, in <module>
    sys.exit(main())
             ^^^^^^

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/main.py", line 241, in main
    agent_config = load_agent_config(**vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/configuration/agent_config_loader.py", line 45, in load_agent_config
    raise DatusException(

datus.utils.exceptions.DatusException: error_code=100002, error_message=Agent configuration file not found, please run with --config <your_config_file_path>
[0m [[0m[1m[34mexception[0m][0m
[2m2025-07-06 13:56:31[0m [[31m[1merror    [0m] [1mExecution failed: Traceback (most recent call last):

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/main.py", line 287, in <module>
    sys.exit(main())
             ^^^^^^

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/main.py", line 241, in main
    agent_config = load_agent_config(**vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/configuration/agent_config_loader.py", line 45, in load_agent_config
    raise DatusException(

datus.utils.exceptions.DatusException: error_code=100002, error_message=Agent configuration file not found, please run with --config <your_config_file_path>
[0m [[0m[1m[34mexception[0m][0m
[2m2025-07-06 13:56:47[0m [[31m[1merror    [0m] [1mExecution failed: Traceback (most recent call last):

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/main.py", line 287, in <module>
    sys.exit(main())
             ^^^^^^

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/main.py", line 241, in main
    agent_config = load_agent_config(**vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/configuration/agent_config_loader.py", line 45, in load_agent_config
    raise DatusException(

datus.utils.exceptions.DatusException: error_code=100002, error_message=Agent configuration file not found, please run with --config <your_config_file_path>
[0m [[0m[1m[34mexception[0m][0m
[2m2025-07-06 13:57:21[0m [[31m[1merror    [0m] [1mExecution failed: Traceback (most recent call last):

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/main.py", line 287, in <module>
    sys.exit(main())
             ^^^^^^

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/main.py", line 241, in main
    agent_config = load_agent_config(**vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/configuration/agent_config_loader.py", line 45, in load_agent_config
    raise DatusException(

datus.utils.exceptions.DatusException: error_code=100002, error_message=Agent configuration file not found, please run with --config <your_config_file_path>
[0m [[0m[1m[34mexception[0m][0m
[2m2025-07-06 13:57:37[0m [[31m[1merror    [0m] [1mExecution failed: Traceback (most recent call last):

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/main.py", line 287, in <module>
    sys.exit(main())
             ^^^^^^

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/main.py", line 241, in main
    agent_config = load_agent_config(**vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/configuration/agent_config_loader.py", line 45, in load_agent_config
    raise DatusException(

datus.utils.exceptions.DatusException: error_code=100002, error_message=Agent configuration file not found, please run with --config <your_config_file_path>
[0m [[0m[1m[34mexception[0m][0m
[2m2025-07-06 13:57:58[0m [[31m[1merror    [0m] [1mExecution failed: Traceback (most recent call last):

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/main.py", line 287, in <module>
    sys.exit(main())
             ^^^^^^

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/main.py", line 241, in main
    agent_config = load_agent_config(**vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/configuration/agent_config_loader.py", line 51, in load_agent_config
    raise DatusException(

datus.utils.exceptions.DatusException: error_code=100002, error_message=Agent configuration file not found: conf/agent.yml
[0m [[0m[1m[34mexception[0m][0m
[2m2025-07-06 13:58:34[0m [[31m[1merror    [0m] [1mExecution failed: Traceback (most recent call last):

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/main.py", line 287, in <module>
    sys.exit(main())
             ^^^^^^

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/main.py", line 241, in main
    agent_config = load_agent_config(**vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/configuration/agent_config_loader.py", line 51, in load_agent_config
    raise DatusException(

datus.utils.exceptions.DatusException: error_code=100002, error_message=Agent configuration file not found: conf/agent.yml
[0m [[0m[1m[34mexception[0m][0m
[2m2025-07-06 13:59:02[0m [[31m[1merror    [0m] [1mExecution failed: Traceback (most recent call last):

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/main.py", line 287, in <module>
    sys.exit(main())
             ^^^^^^

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/main.py", line 241, in main
    agent_config = load_agent_config(**vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/linghongbo/AIdeaProjects/Datus-agent/datus/configuration/agent_config_loader.py", line 51, in load_agent_config
    raise DatusException(

datus.utils.exceptions.DatusException: error_code=100002, error_message=Agent configuration file not found: conf/agent.yml
[0m [[0m[1m[34mexception[0m][0m
